name: CI - Test&Build
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # keeps GitHub from removing runner due to inactivity
jobs:
  test:
    runs-on: LV20x64
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        shell: bash
        run: ./run_unittests.sh

