name: CI - Test&Build
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # keeps GitHub from removing runner due to inactivity
jobs:
  test:
    runs-on: LV20x64
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        shell: bash
        run: -./run_unittests.sh
      - name: Build Package
        shell: bash
        run: -./build.sh $GITHUB_RUN_NUMBER  
      - name: Install 
        run: -g-cli vip -- -local-vip-file "$(ls build/*.vip)" -v "20.0 (64-bit)"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'

